include: package:flutter_lints/flutter.yaml

linter:
  rules:
    #    Development false else true
    prefer_const_constructors: false
    avoid_print: false
    prefer_const_declarations: false
    avoid_unnecessary_containers: false
    prefer_const_literals_to_create_immutables: false
    sized_box_for_whitespace: false

    #    Must stay false
    prefer_is_empty: true
    file_names: true
    library_prefixes: true
    camel_case_types: true
    constant_identifier_names: true