name: flutter_playground
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  particles_flutter: ^0.1.4
  http: ^0.13.4
  get: ^4.3.8
  flutter_svg: ^1.0.3
  avatars: ^3.0.2
  syncfusion_flutter_calendar: ^20.1.51
  webview_flutter: ^3.0.2
  flutter_html: ^3.0.0-alpha.3
  syncfusion_flutter_datepicker: ^20.1.51
  google_fonts: ^2.1.0
  show_up_animation: ^2.0.0
  animations: ^2.0.2
  cupertino_back_gesture: ^0.1.0
  swipeable_page_route: ^0.2.4
  scroll_to_index: ^2.1.0
  super_tooltip: ^1.0.1
  syncfusion_localizations: ^20.1.51
  flutter_quill: ^4.0.9
  video_editor: ^1.4.3
#  ffmpeg_kit_flutter: ^4.5.1
  tapioca: ^1.0.6+1
  helpers: ^1.1.4
  crypto: ^3.0.2
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang-Bold.ttf
          weight: 700
        - asset: assets/fonts/Battambang-Regular.ttf
          weight: 400
    - family: Moul
      fonts:
        - asset: assets/fonts/Moul-Regular.ttf
    - family: KhmerOSBattambang
      fonts:
        - asset: assets/fonts/KhmerOS_battambang.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: KohSantepheap
      fonts:
        - asset: assets/fonts/KohSantepheap-Black.ttf
        - asset: assets/fonts/KohSantepheap-Bold.ttf
        - asset: assets/fonts/KohSantepheap-Light.ttf
        - asset: assets/fonts/KohSantepheap-Regular.ttf
        - asset: assets/fonts/KohSantepheap-Thin.ttf
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/id_icon.ttf

  assets:
    - assets/images/mptc_logo.png
    - assets/images/sim_history.png
    - assets/images/swap_sim.png
    - assets/images/app_logo2.png
    - assets/images/khmer_flag.jpg
    - assets/images/english_flag.jpg
    - assets/images/cellcard.png
    - assets/images/cooltel.png
    - assets/images/metfone.png
    - assets/images/qb.jpg
    - assets/images/seatel.jpg
    - assets/images/smart.jpg
    - assets/images/success.png
    - assets/images/fail.png
    - assets/images/nointernet.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
